import {fontScale} from '../utils/scaling';

const FONT_FAMILY = {
  EXTRA_LIGHT: 'Sora-ExtraLight',
  LIGHT: 'Sora-Light',
  THIN: 'Sora-Thin',
  MEDIUM: 'Sora-Medium',
  REGULAR: 'Sora-Regular',
  SEMI_BOLD: 'Sora-SemiBold',
  BOLD: 'Sora-Bold',
  EXTRA_BOLD: 'Sora-ExtraBold',
};

export const FONT = {
  displayLarge: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(64),
    fontSize: fontScale(57),
    fontWeight: '400',
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(52),
    fontSize: fontScale(45),
    fontWeight: '400',
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(44),
    fontSize: fontScale(36),
    fontWeight: '400',
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(40),
    fontSize: fontScale(32),
    fontWeight: '400',
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(36),
    fontSize: fontScale(28),
    fontWeight: '400',
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(32),
    fontSize: fontScale(24),
    fontWeight: '400',
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(28),
    fontSize: fontScale(22),
    fontWeight: '400',
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(24),
    fontSize: fontScale(16),
    fontWeight: '500',
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(20),
    fontSize: fontScale(14),
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  labelLarge: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(20),
    fontSize: fontScale(14),
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(16),
    fontSize: fontScale(12),
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(16),
    fontSize: fontScale(11),
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  bodyLarge: {
    fontFamily: FONT_FAMILY.MEDIUM,
    lineHeight: fontScale(24),
    fontSize: fontScale(16),
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(20),
    fontSize: fontScale(14),
    fontWeight: '400',
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: FONT_FAMILY.REGULAR,
    lineHeight: fontScale(16),
    fontSize: fontScale(12),
    fontWeight: '400',
    letterSpacing: 0.4,
  },
};
